version: '3'

services:
  ext_proc_demo_envoy:
    image: envoyproxy/envoy-dev:latest
    container_name: ext_proc_demo_envoy
    entrypoint: /usr/local/bin/envoy
    command:
      [
        "--config-path",
        "/etc/envoy/envoy.yaml",
        "--log-level",
        "${ENVOY_LOG_LEVEL:-info}",
        "--service-cluster",
        "envoy-front",
        "--service-node",
        "envoy-front"
      ]
    ports:
      - 10000:10000
      - 15000:15000
    networks:
      - ext-proc-demo-network
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  ext_proc_demo_service:
    image: containous/whoami:latest
    expose:
      - 80
    networks:
      - ext-proc-demo-network

  ext_proc_demo_ext_proc:
    container_name: ext_proc_demo_ext_proc
    build:
      context: ./
    environment:
      CLUSTER_NAME: "ext_proc"
    expose:
      - 50051
    networks:
      - ext-proc-demo-network

  # debug traces with http://localhost:55679/debug/tracez
  opentelemetry:
    build:
      context: .
      dockerfile: Dockerfile-opentelemetry
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sf http://localhost:13133 || exit 1"
        ]
      interval: 1s
      timeout: 120s
      retries: 120
      start_period: 5s
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "55679:55679"
    networks:
      - ext-proc-demo-network

networks:
  ext-proc-demo-network:
    driver: bridge
